// Generated by CoffeeScript 1.4.0
(function() {
  var Fish;

  Fish = (function() {

    function Fish(options) {
      var _this = this;
      this.options = options;
      this.el = $('<div class="fish">魚</div>');
      this.el.css({
        'color': this.options.color,
        'border-color': this.options.color
      });
      this.el.on('mouseenter', function() {
        return _this.stop();
      });
    }

    Fish.prototype.startMoving = function() {
      var s, toLeft, toRight,
        _this = this;
      toRight = {
        left: 10
      };
      toLeft = {
        left: -10
      };
      s = this.options.speed;
      this.el.animate(toRight, s);
      this.el.animate(toLeft, s, function() {
        return _this.startMoving();
      });
      return this;
    };

    Fish.prototype.stop = function() {
      this.el.stop(true);
      return this;
    };

    return Fish;

  })();

  $(function() {
    var $aquarium, fish1, fish2, fish3;
    fish1 = new Fish({
      speed: 200,
      color: 'red'
    });
    fish2 = new Fish({
      speed: 300,
      color: 'orange'
    });
    fish3 = new Fish({
      speed: 400,
      color: 'blue'
    });
    $aquarium = $('#aquarium');
    $aquarium.append(fish1.el);
    $aquarium.append(fish2.el);
    $aquarium.append(fish3.el);
    $('#start').click(function() {
      fish1.startMoving();
      fish2.startMoving();
      return fish3.startMoving();
    });
    return $('#stop').click(function() {
      fish1.stop();
      fish2.stop();
      return fish3.stop();
    });
  });

}).call(this);
