// Generated by CoffeeScript 1.4.0
(function() {
  var EventModule, ev;

  EventModule = (function() {

    function EventModule() {}

    EventModule.prototype.on = function(name, callback) {
      if (this.callbacks == null) {
        this.callbacks = {};
      }
      if (this.callbacks[name] == null) {
        this.callbacks[name] = [];
      }
      this.callbacks[name].push(callback);
      return this;
    };

    EventModule.prototype.trigger = function(name) {
      var callback, list, _i, _len, _ref;
      list = (_ref = this.callbacks) != null ? _ref[name] : void 0;
      if (!list) {
        return this;
      }
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        callback = list[_i];
        callback();
      }
      return this;
    };

    return EventModule;

  })();

  ev = new EventModule;

  ev.on('foo', function() {
    return alert('foo!');
  });

  ev.trigger('foo');

  ev.on('bar', function() {
    return alert('bar1!');
  });

  ev.on('bar', function() {
    return alert('bar2!');
  });

  ev.on('bar', function() {
    return alert('bar3!');
  });

  ev.trigger('bar');

}).call(this);
