// Generated by CoffeeScript 1.4.0
(function() {
  var Light;

  Light = (function() {

    function Light() {
      var _this = this;
      this.powered = false;
      this.powerOnCallbacks = [];
      this.powerOffCallbacks = [];
      this.el = $('#light');
      this.el.click(function() {
        return _this.toggle();
      });
    }

    Light.prototype.powerOn = function() {
      var callback, _i, _len, _ref;
      this.powered = true;
      this.el.css('background', 'yellow');
      _ref = this.powerOnCallbacks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        callback = _ref[_i];
        callback();
      }
      return this;
    };

    Light.prototype.powerOff = function() {
      var callback, _i, _len, _ref;
      this.powered = false;
      this.el.css('background', 'white');
      _ref = this.powerOffCallbacks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        callback = _ref[_i];
        callback();
      }
      return this;
    };

    Light.prototype.toggle = function() {
      if (this.powered) {
        this.powerOff();
      } else {
        this.powerOn();
      }
      return this;
    };

    Light.prototype.onPowerOn = function(callback) {
      this.powerOnCallbacks.push(callback);
      return this;
    };

    Light.prototype.onPowerOff = function(callback) {
      this.powerOffCallbacks.push(callback);
      return this;
    };

    return Light;

  })();

  $(function() {
    var light;
    light = new Light;
    light.onPowerOn(function() {
      return alert('light on!');
    });
    return light.onPowerOff(function() {
      return alert('light off!');
    });
  });

}).call(this);
