// Generated by CoffeeScript 1.4.0
(function() {
  var Aquarium, Fish;

  Fish = (function() {

    function Fish(options) {
      var _this = this;
      this.options = options;
      this.el = $('<div class="fish">魚</div>');
      this.el.css({
        'color': this.options.color,
        'border-color': this.options.color
      });
      this.el.on('mouseenter', function() {
        return _this.stop();
      });
    }

    Fish.prototype.startMoving = function() {
      var s, toLeft, toRight,
        _this = this;
      toRight = {
        left: 10
      };
      toLeft = {
        left: -10
      };
      s = this.options.speed;
      this.el.animate(toRight, s);
      this.el.animate(toLeft, s, function() {
        return _this.startMoving();
      });
      return this;
    };

    Fish.prototype.stop = function() {
      this.el.stop(true);
      return this;
    };

    return Fish;

  })();

  Aquarium = (function() {

    function Aquarium() {
      this.el = $('#aquarium');
      this.fishItems = [];
    }

    Aquarium.prototype.addFish = function(options) {
      var fish;
      fish = new Fish(options);
      this.el.append(fish.el);
      this.fishItems.push(fish);
      return this;
    };

    Aquarium.prototype.startAll = function() {
      $.each(this.fishItems, function(i, fish) {
        return fish.startMoving();
      });
      return this;
    };

    Aquarium.prototype.stopAll = function() {
      $.each(this.fishItems, function(i, fish) {
        return fish.stop();
      });
      return this;
    };

    return Aquarium;

  })();

  $(function() {
    var aquarium;
    aquarium = new Aquarium;
    aquarium.addFish({
      speed: 200,
      color: 'red'
    });
    aquarium.addFish({
      speed: 300,
      color: 'orange'
    });
    aquarium.addFish({
      speed: 400,
      color: 'blue'
    });
    $('#start').click(function() {
      return aquarium.startAll();
    });
    return $('#stop').click(function() {
      return aquarium.stopAll();
    });
  });

}).call(this);
