// Generated by CoffeeScript 1.4.0
(function() {
  var Fish;

  Fish = (function() {

    function Fish() {
      this.el = $('<div class="fish">魚</div>');
    }

    return Fish;

  })();

  $(function() {
    var $aquarium, fish1, fish2, fish3;
    fish1 = new Fish;
    fish2 = new Fish;
    fish3 = new Fish;
    $aquarium = $('#aquarium');
    $aquarium.append(fish1.el);
    $aquarium.append(fish2.el);
    return $aquarium.append(fish3.el);
  });

}).call(this);
