// Generated by CoffeeScript 1.4.0
(function() {
  var Light;

  Light = (function() {

    function Light() {
      var _this = this;
      this.powered = false;
      this.el = $('#light');
      this.el.click(function() {
        return _this.toggle();
      });
    }

    Light.prototype.powerOn = function() {
      this.powered = true;
      this.el.css('background', 'yellow');
      return this;
    };

    Light.prototype.powerOff = function() {
      this.powered = false;
      this.el.css('background', 'white');
      return this;
    };

    Light.prototype.toggle = function() {
      if (this.powered) {
        this.powerOff();
      } else {
        this.powerOn();
      }
      return this;
    };

    return Light;

  })();

  $(function() {
    var light;
    return light = new Light;
  });

}).call(this);
