// Generated by CoffeeScript 1.4.0
(function() {
  var Aquarium, EventModule, Fish, Light, randomNum,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  randomNum = function(from, to) {
    var floor, random;
    floor = Math.floor;
    random = Math.random;
    return from + floor(random() * (to - from + 1));
  };

  EventModule = (function() {

    function EventModule() {}

    EventModule.prototype.on = function(name, callback) {
      if (this.callbacks == null) {
        this.callbacks = {};
      }
      if (this.callbacks[name] == null) {
        this.callbacks[name] = [];
      }
      this.callbacks[name].push(callback);
      return this;
    };

    EventModule.prototype.trigger = function(name) {
      var callback, list, _i, _len, _ref;
      list = (_ref = this.callbacks) != null ? _ref[name] : void 0;
      if (!list) {
        return this;
      }
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        callback = list[_i];
        callback();
      }
      return this;
    };

    return EventModule;

  })();

  Light = (function(_super) {

    __extends(Light, _super);

    function Light() {
      var _this = this;
      this.powered = false;
      this.el = $('#light');
      this.el.click(function() {
        return _this.toggle();
      });
    }

    Light.prototype.powerOn = function() {
      this.powered = true;
      this.el.css('background', 'yellow');
      this.trigger('poweron');
      return this;
    };

    Light.prototype.powerOff = function() {
      this.powered = false;
      this.el.css('background', 'white');
      this.trigger('poweroff');
      return this;
    };

    Light.prototype.toggle = function() {
      if (this.powered) {
        this.powerOff();
      } else {
        this.powerOn();
      }
      return this;
    };

    return Light;

  })(EventModule);

  Fish = (function() {

    function Fish(options) {
      this.options = options;
      this.prepareEls();
      this.handleColors();
      this.eventify();
      this.positionRandomly();
    }

    Fish.prototype.prepareEls = function() {
      this.el = $('<div class="fish"><div>魚</div></div>');
      this.inner = $('div', this.el);
      return this;
    };

    Fish.prototype.handleColors = function() {
      this.inner.css({
        'color': this.options.color,
        'border-color': this.options.color
      });
      return this;
    };

    Fish.prototype.eventify = function() {
      var _this = this;
      this.el.on('mouseenter', function() {
        return _this.stop();
      });
      return this;
    };

    Fish.prototype.positionRandomly = function() {
      this.el.css({
        left: randomNum(20, 260),
        top: randomNum(20, 160)
      });
      return this;
    };

    Fish.prototype.startMoving = function() {
      var s, toLeft, toRight,
        _this = this;
      toRight = {
        left: 10
      };
      toLeft = {
        left: -10
      };
      s = this.options.speed;
      this.inner.animate(toRight, s);
      this.inner.animate(toLeft, s, function() {
        return _this.startMoving();
      });
      return this;
    };

    Fish.prototype.stop = function() {
      this.inner.stop(true);
      return this;
    };

    return Fish;

  })();

  Aquarium = (function() {

    function Aquarium() {
      this.el = $('#aquarium');
      this.fishItems = [];
    }

    Aquarium.prototype.addFish = function(options) {
      var fish;
      fish = new Fish(options);
      this.el.append(fish.el);
      this.fishItems.push(fish);
      return this;
    };

    Aquarium.prototype.startAll = function() {
      $.each(this.fishItems, function(i, fish) {
        return fish.startMoving();
      });
      return this;
    };

    Aquarium.prototype.stopAll = function() {
      $.each(this.fishItems, function(i, fish) {
        return fish.stop();
      });
      return this;
    };

    return Aquarium;

  })();

  $(function() {
    var aquarium, light;
    aquarium = new Aquarium;
    light = new Light;
    aquarium.addFish({
      speed: 200,
      color: 'red'
    });
    aquarium.addFish({
      speed: 300,
      color: 'orange'
    });
    aquarium.addFish({
      speed: 400,
      color: 'blue'
    });
    light.on('poweron', function() {
      return aquarium.startAll();
    });
    return light.on('poweroff', function() {
      return aquarium.stopAll();
    });
  });

}).call(this);
